title: Title of your CV site
profile_img: /assets/img/profile.webp
icon_img: /assets/img/icon.webp

name: "Matthew Hatami"
job: "〈PhD Student | Disaster Researcher | Aspiring Geospatial Data Scientist〉"

phone_number: +39 331 253 8654
address: Columbia, SC, USA
email: mhatami@sc.edu
linkedin_username: https://www.linkedin.com/in/matthewhatami/
github_username: https://github.com/MatthewHatami
instagram_username: matthew.scholar
twitter_username: https://x.com/matthewhatami1
facebook_username: facebook
youtube_username: youtube
blog_url: https://matthewhatami.github.io

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag